### ISSUE TITLE
Python code for quick sort

### ISSUE THREAD

**Issue by deepshikha2708** [Saikat2407/DSA_Hacktoberfest#13]
can you assign me this issue

**Comment by Saikat2407** [comment]
Yeah, sure!!

**Comment by Saikat2407** [comment]
make sure to add programs under respective folder.

**Comment by Saikat2407** [comment]
don't forget to star the repo.

**Comment by akash9579** [comment]
Hi @Saikat2407 
Can u assign me this issue
I am happy to contribute on this.

**Comment by Saikat2407** [comment]
> Hi @Saikat2407 Can u assign me this issue I am happy to contribute on this.

sure!

**Comment by sona-123** [comment]
Hi @Saikat2407 Can you please assign this issue to me I want to contribute on this

**Comment by Saikat2407** [comment]
sure work on it asap!!

**Comment by Saikat2407** [comment]
> Hi @Saikat2407 Can you please assign this issue to me I want to contribute on this

sure, star the repo first and start working on it!!

**Comment by shouryakhanka** [comment]
Hi @Saikat2407  can i work on this issue?
