### ISSUE TITLE
leetcode problem house robber uisng dp 

### ISSUE THREAD

**Issue by Shobhnik13** [Saikat2407/DSA_Hacktoberfest#21]

**Comment by shouryakhanka** [comment]
Hey @Saikat2407 can you assign this to me?

**Comment by Saikat2407** [comment]
work on it asap!

**Comment by Shobhnik13** [comment]
hey i just made a pr please check it out

**Comment by Abulaman23** [comment]
Hello @Saikat2407 ,could you please assign this to me!

**Comment by Saikat2407** [comment]
> Hello @Saikat2407 ,could you please assign this to me!

Already been solved, meanwhile if you want to solve any other issue let me know.
