### ISSUE TITLE
C++ codes

### ISSUE THREAD

**Issue by debapriya36** [Saikat2407/DSA_Hacktoberfest#4]
Hi, @Saikat2407  can you assign this issue to me?
problems links:
https://leetcode.com/problems/longest-palindromic-subsequence/
https://leetcode.com/problems/edit-distance/
https://leetcode.com/problems/delete-operation-for-two-strings/
https://leetcode.com/problems/longest-common-subsequence/

**Comment by Saikat2407** [comment]
Star the Repo, and make sure to make a separate folder named it as leetcode and dont forget to add the question link.

**Comment by debapriya36** [comment]
how to add a folder? There is only add file option!

**Comment by Saikat2407** [comment]
star the repo first.
fork the repo.
go to vscode or any ide you have and go to terminal and type [git clone - url]
open in the folder from the local disk and make folder inside the folder(named it as leetcode)
upload the files and commit and push.

**Comment by Saikat2407** [comment]
> After folder adding , then what i need to do ?

create a pull request and you are good to go!!

**Comment by debapriya36** [comment]
thanks for guiding :)

**Comment by debapriya36** [comment]
adding 4 problems is equal to 1 valid pr or 4 valid pr?

**Comment by Saikat2407** [comment]
> adding 4 problems is equal to 1 valid pr or 4 valid pr?

1 pr = 1 valid pr .

**Comment by debapriya36** [comment]
i am facing issue with push commands, showing err

**Comment by debapriya36** [comment]
can you share the push commands?

**Comment by Saikat2407** [comment]
check the (getting started) section from Readme.md file!!

**Comment by debapriya36** [comment]
I think , i have done the commit and push! plz check!

**Comment by Saikat2407** [comment]
Yes checked and reviewed, need some changes make sure ypu complete that and on completion i will merge it to the main.
happy coding and good job man.

**Comment by debapriya36** [comment]
yes! i edited my files  now:)

**Comment by Saikat2407** [comment]
Yeah 👍 !!

**Comment by Saikat2407** [comment]
Don't forget to follow me, if you find me helpful, happy coding

**Comment by debapriya36** [comment]
Is it successfully merged?
Yes i am following you 👍 
thanks for helping

**Comment by Saikat2407** [comment]
Yeah its merged!!
