### ISSUE TITLE
Find First and Last occurance of element in sorted array

### ISSUE THREAD

**Issue by priyanshuhaldar007** [Saikat2407/DSA_Hacktoberfest#47]
[Leetcode question No 34](https://leetcode.com/problems/find-first-and-last-position-of-element-in-sorted-array/)

Please assign this to me

**Comment by Saikat2407** [comment]
@priyanshuhaldar007 kindly Add up your solution with question link on top of the file and push it under leetcode folder

**Comment by Abulaman23** [comment]
Please assign this to me!

**Comment by Saikat2407** [comment]
> Please assign this to me!

assigned

**Comment by pritam1309** [comment]
plz assign it to me

**Comment by Saikat2407** [comment]
> plz assign it to me

sure

**Comment by nithish12345678** [comment]
Hi 
@priyanshuhaldar007 , I am interested to look into this issue. if the issue is not yet resolved , Would you please assign this to me ?

**Comment by Saikat2407** [comment]
> Hi @Saikat2407 , I am interested to look into this issue. if the issue is not yet resolved , Would you please assign this to me ?

sure man!

**Comment by DeveVivek** [comment]
Please assign me this issue.

**Comment by Saikat2407** [comment]
> Please assign me this issue.

Add up and make a PR.
