### ISSUE TITLE
Make changes in leetcode folder.

### ISSUE THREAD

**Issue by Saikat2407** [Saikat2407/DSA_Hacktoberfest#59]
solve the issue #21

**Comment by MauryaD** [comment]
Hi @Saikat2407 ,
Please assign it to me. I would add more LeetCode problem-solution.
Thanks!

**Comment by Saikat2407** [comment]
@MauryaD Do it asap and if u find this repo useful do share and star the repo 👍

**Comment by MauryaD** [comment]
Sure @Saikat2407 !
I've added PR #66 . Willl add more soon. Meanwhile could you please review and merge this one.
Also, I more request please. Please add the Hacktoberfest labels to the issue.

Thanks!
