### ISSUE TITLE
Correction_insertion_sort

### ISSUE THREAD

**Issue by Kdeveloper2000** [Saikat2407/DSA_Hacktoberfest#6]
The given code will sort it in decreasing order and there is a bug in it.

**Comment by Kdeveloper2000** [comment]
Can you please assign it to me? I will be very grateful.

**Comment by Saikat2407** [comment]
star the repo and start solving the bug, and don't forget to add the specific file in whatever language you are using.

**Comment by Kdeveloper2000** [comment]
already star the repo and solved the bug. Please assign it to me.

**Comment by Saikat2407** [comment]
Start working, I've already assigned it to you.

**Comment by Kdeveloper2000** [comment]
Done.
