### ISSUE TITLE
Contribute a Spring Boot Application

### ISSUE THREAD

**Issue by Anirban-Chand** [Saikat2407/DSA_Hacktoberfest#63]
I want to contribute a spring boot application demonstrating the Restful CRUD APIs. Can I work on this? If yes then where should I put it Java_Imp->Spring Boot OR a New Folder(Spring Boot) on the main directory?

**Comment by Saikat2407** [comment]
Add a new folder in  the main and name it as Java Framework and under that directory make a new folder(spring boot) and push the code @Anirban-Chand
