### ISSUE TITLE
add this link on top of the file 

### ISSUE THREAD

**Issue by Saikat2407** [Saikat2407/DSA_Hacktoberfest#64]
Add    //https://leetcode.com/problems/path-sum/ on top of the file of #10

**Comment by DarkSoul26** [comment]
@Saikat2407 can you assign it to me

**Comment by Saikat2407** [comment]
@DarkSoul26 work on it asap!

**Comment by DarkSoul26** [comment]
I looked into the file and I can notice that the problem link is already added to the file.

<img width="475" alt="image" src="https://user-images.githubusercontent.com/60578902/195782064-d58e7e61-0760-4086-9e58-332da7b16d00.png">
